version: '3'
services:
   myweb :
      # image: php:7.4-apache
      build:
         context: .
         dockerfile: ./web/Dockerfile
      volumes:
         - ./web:/var/www/html
      environment:
         - VIRTUAL_HOST=www.nitkpc.com
         - VIRTUAL_PORT=80
         - LETSENCRYPT_HOST=www.nitkpc.com
      ports:
         - 80
      container_name: myweb
      networks:
         - proxy-network
         - db-internal
   mydb:
      image: mysql:latest
      # build:
      #    context: .
      #    dockerfile: ./db/Dockerfile
      volumes:
         - ./db/init:/docker-entrypoint-initdb.d
      environment:
         - MYSQL_ROOT_PASSWORD=hogehoge
         - MYSQL_PORT=3306
         - MYSQL_DATABASE=members
         - MYSQL_USER=admin
         - MYSQL_PASSWORD=fugafuga
      ports:
         - 3306:3306
      container_name: mydb
      networks:
        - db-internal

networks:
  default:
  proxy-network:
    external: true
  db-internal:
