version: '3'
services:
   myweb :
      image: php:7.4-apache
      build:
         context: .
         dockerfile: ./web/Dockerfile
      volumes:
         - ./web:/var/www/html
      ports:
         - 8080:80
      restert: always
      container_name: myweb
   mydb:
      image: mysql:latest
      volumes:
         - ./db/init:/docker-entrypoint-initdb.d
      environment:
         - MYSQL_ROOT_PASSWORD=hogehoge
         - MYSQL_PORT=3306
         - MYSQL_DATABASE=members
         - MYSQL_USER=admin
         - MYSQL_PASSWORD=fugafuga
      ports:
         - 3306:3306
      restart: always
      container_name: mydb

